stages:
  - lint
  - test
  - build
  - deploy

lint:
  stage: lint
  image: python:3.8
  script:
    - pip install pylint
    - pylint "flashcard-trainer/static"
  allow_failure: true

test1:
  stage: test
  image: python:3.8
  script:
    - pip install -r requirements.txt

test2:
  stage: test
  image: python:3.8
  script:
    - pip install -r requirements.txt

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    - docker run -d -p 5000:5000 "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  environment:
    name: production
    url: http://127.0.0.1:5000  # Replace <your-server-ip> with the actual server IP or domain
